CREATE TABLE PERSONAS (
CODPERSONA NUMBER(3) PRIMARY KEY,
NOMPERSONA VARCHAR2(20),
EDAD NUMBER (2),
SEXO VARCHAR2(10)
);

INSERT INTO PERSONAS VALUES (001,’LUIS’,20,’HOMBRE’);
INSERT INTO PERSONAS VALUES (002,’LUISA",21,’MUJER’);
INSERT INTO PERSONAS VALUES (003,’FERNANDO’,30,’HOMBRE’);
INSERT INTO PERSONAS VALUES (004,’CARMEN’,40,’MUJER’);
INSERT INTO PERSONAS VALUES (005,’JESUS’,40,’HOMBRE’);
COMMIT;