CREATE TABLE PERSONAS
(
    DNI    VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PERSONAS PRIMARY KEY (DNI)
);

CREATE TABLE MULTAS
(
    REF       VARCHAR2(20),
    MATRICULA VARCHAR2(10) NOT NULL,
    IMPORTE   NUMBER(6, 2) NOT NULL,
    LUGAR     VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_MULTAS PRIMARY KEY (REF)
);

CREATE TABLE MATRICULAS
(
    MATRICULA VARCHAR2(10) NOT NULL,
    DNI       VARCHAR2(10) NOT NULL,
    REF       VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MATRICULAS PRIMARY KEY (MATRICULA),
    CONSTRAINT FK_MATRICULAS_PERSONAS FOREIGN KEY (DNI) REFERENCES PERSONAS (DNI),
    CONSTRAINT FK_MATRICULAS_MULTAS FOREIGN KEY (REF) REFERENCES MULTAS (REF)
);