CREATE TABLE ASIGNATURAS(
     NOMASIG      VARCHAR2(20),
	 HORASCREDITO NUMBER(2),
	 SEMESTRE     VARCHAR2(15),
	 PROFESOR     VARCHAR2(15)
);

INSERT INTO ASIGNATURAS VALUES ('GEOGRAFIA',3,'OTOÑO','BLANC');
INSERT INTO ASIGNATURAS VALUES ('ARQUITECTURA',5,'VERANO','SMITH');
INSERT INTO ASIGNATURAS VALUES ('TRIGONOMETRIA',3,'PRIMAVERA','WEEKS');
INSERT INTO ASIGNATURAS VALUES ('PLANIFICACION',2,'PRIMAVERA','JONES');
INSERT INTO ASIGNATURAS VALUES ('SICOLOGIA',3,'OTOÑO','MARTIN');
INSERT INTO ASIGNATURAS VALUES ('SICOLOGIA',3,'PRIMAVERA','GERBER');
INSERT INTO ASIGNATURAS VALUES ('SICOLOGIA',3,'OTOÑO','GERBER');
INSERT INTO ASIGNATURAS VALUES ('SICOLOGIA',3,'PRIMAVERA','MARTIN');
INSERT INTO ASIGNATURAS VALUES ('BIOLOGIA',4,'OTOÑO','GREGORY');
INSERT INTO ASIGNATURAS VALUES ('BIOLOGIA',4,'PRIMAVERA','ALLEN');
INSERT INTO ASIGNATURAS VALUES ('ASTRONOMIA',6,'PRIMAVERA','BARNES');
INSERT INTO ASIGNATURAS VALUES ('BIOLOGIA',3,'VERANO','ALLEN');
INSERT INTO ASIGNATURAS VALUES ('ALGEBRA',2,'VERANO','BLANE');
INSERT INTO ASIGNATURAS VALUES ('ALGEBRA',3,'VERANO','WEEKS');
INSERT INTO ASIGNATURAS VALUES ('CALCULO',3,'INVIERNO','BLANE');
INSERT INTO ASIGNATURAS VALUES ('CALCULO',1,'INVIERNO','WEEKS');


CREATE TABLE PROFESORES(
     NOMPROFESOR VARCHAR2(10) PRIMARY KEY,
     CATEGORIA VARCHAR2(20)
);

INSERT INTO PROFESORES VALUES ('SMITH','PROFESOR AUXILIAR');
INSERT INTO PROFESORES VALUES ('GERBER','PROFESOR AYUDANTE');
INSERT INTO PROFESORES VALUES ('WEEKS','PROFESOR AYUDANTE');
INSERT INTO PROFESORES VALUES ('ALLEN','PROFESOR AUXILIAR');
INSERT INTO PROFESORES VALUES ('BARNES','CATEDRATICO');
INSERT INTO PROFESORES VALUES ('BLANES','PROFESOR AUXILIAR');
INSERT INTO PROFESORES VALUES ('GREGORY','PROFESOR AYUDANTE');
INSERT INTO PROFESORES VALUES ('JONES','PROFESOR AYUDANTE');
INSERT INTO PROFESORES VALUES ('MARTIN','PROFESOR AYUDANTE');